# Generated by Django 6.0.2 on 2026-03-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_rsvps"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.ImageField(
                blank=True, default="default_event.jpg", upload_to="event_images/"
            ),
        ),
    ]
